apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: demo-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/bigkevmcd/pipeline-demo
    - name: revision
      value: 6057b47bdb15849a873dffa649fe534986607635
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: run-test-task
spec:
  taskRef:
    name: test-task
    kind: Task
  inputs:
    params:
    - name: message
      value: This is a message from the TaskRun
    resources:
    - name: source
      resourceRef:
        name: demo-git
      # resourceSpec:
      #   type: git
      #   params:
      #     - name: revision
      #       value: master
      #     - name: url
      #       value: https://github.com/GoogleContainerTools/skaffold
