apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: test-task
spec:
  inputs:
    params:
    - name: message
      description: the message to echo
      default: hello
  steps:
  - image: ubuntu
    script: |
        #!/usr/bin/env bash
        echo $(inputs.params.message)
