apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-log-archiver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tekton-log-archiver
  template:
    metadata:
      labels:
        name: tekton-log-archiver
    spec:
      serviceAccountName: tekton-log-archiver
      containers:
        - name: tekton-log-archiver
          image: quay.io/kmcdermo/log-archiver
          command:
          - tekton-log-archiver
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "tekton-log-archiver"
